name: API CI

on:
  push:
    branches:
      - 'feat/*'
      - '!main'
    paths:
      - api/**

jobs:
  build:
    uses: dragon-ion-za/3ncount3r/.github/workflows/step_build.yml@main
    with:
      sourcePath: "api"
      artifactName: "api"